### ISSUE TITLE
More explanations / benchmark ?

### ISSUE THREAD

**Issue by xxorax** [abbr/deasync#1]
Maybe it need more explanations about the event loop and when the "while" loop is fire, for the people (like me) that don't know the libuv API.

I noticed that more there is async call after calling deasync(fn)(), more there is loop in the "while" (I just put a console.log after binding.run() to see it)

So what will append if you do it on an http server for example ?
Finaly, how this reduces the performances ?

Thanks

**Comment by abbr** [comment]
No explanation can be more convincing than launching a benchmark test and seeing the result yourself. All it needs is taking the 3rd example, bumping up timeout parameter, running it, and monitoring the cpu usage.

**Comment by JounQin** [comment]
I have a benchmark at https://github.com/rx-ts/synckit/blob/perf/make-synchronous/benchmarks/benchmark.txt

It seems it is almost the same as `worker_threads` solution, while `worker_threads` does not require node bindings.
