### ISSUE TITLE
Trying to use with browserify fails

### ISSUE THREAD

**Issue by tnrich** [abbr/deasync#10]
It appears that this is a "browserifyable" package according to Browserify Search (fig1), but I am struggling to get it to work (fig 2). Could it be that it actually can't be used in the browser? It seems likely because in the description it says it relies on node and the point of failure appears to be on a lookup to a node variable.

Just want to confirm that this is true, and also to recommend to y'all that you make this limitation maybe a bit more visible in the docs. 

Thanks! 
-Thomas

Fig 1:
![image](https://cloud.githubusercontent.com/assets/2730609/6630920/bbcfac88-c8db-11e4-890f-ccb5febb4712.png)

Fig 2:
![image](https://cloud.githubusercontent.com/assets/2730609/6630912/9fabdefa-c8db-11e4-86f3-d783fa31e7c9.png)

**Comment by abbr** [comment]
`deasync` depends on `Node`. You should submit issue report to Browserify Search per its [Readme](https://github.com/browserify-search/www#feedback).

**Comment by tnrich** [comment]
Will do.

**Comment by gandhirajan** [comment]
@tnrich Did you made it working using browserify?

**Comment by tnrich** [comment]
@gandhirajan no I never did
