### ISSUE TITLE
Deasync hangs in spawned process ?

### ISSUE THREAD

**Issue by jardicc** [abbr/deasync#119]
I am using node-webkit and cross-spawn to spawn NodeJS child process and inside this process, I am using deasync. And it hangs when event listeners trigger code with deasync inside in short period of time. 

But when I run NodeJS as a standalone process instead of child process then it doesn't seem to happen.

I can't send code to reproduce yet so I am just telling my suspicion

**Comment by abbr** [comment]
Should be fixed since v0.1.17.
