### ISSUE TITLE
node 15.x support.

### ISSUE THREAD

**Issue by liudonghua123** [abbr/deasync#135]
I could not install `deasync` in node 15.x. However I can use old version like `14.x` to install it, then copy `%appdata%\npm\node_modules\mdy\node_modules\deasync\bin\win32-x64-node-14` to `%appdata%\npm\node_modules\mdy\node_modules\deasync\bin\win32-x64-node-15` to make it work for node 15.x.

Please add node `15.x` support.

**Comment by abbr** [comment]
Published deasync@0.1.21 to support node 15
