### ISSUE TITLE
Context issue

### ISSUE THREAD

**Issue by CliffS** [abbr/deasync#16]
There seems to be a context issue whereby `this` is wrong. This applies where the function passed to deasync() is a method on a class.

This is where it came up for me:

    var dbh = mySQL.createConnection(db);
    var query = deasync(dbh.query);
    var rows = query(sql, [ params ]);

The first call inside `Connection.query()` is `this._implyConnect();` but this fails because `this` is not set to an instance of `Connection`.

I'm not sure of the best way to fix this.  I'm hoping you have more ideas than I do. :-)

**Comment by abbr** [comment]
Seems to be a duplication of issue #5. Close for now unless the proposed solution doesn't work for you.

**Comment by CliffS** [comment]
Apologies, I'd missed the answer reading through.

`bind` works well.  Possibly worth adding it to the README?

Thanks for your response and for the module.
