### ISSUE TITLE
linux cant install deasync

### ISSUE THREAD

**Issue by YangLG-7** [abbr/deasync#162]
in linux、node  version 14.16，I try so many version,like ` 0.1.25 0.1.16 0.1.24`

It showed the mistake `Cannot find module '/xxxxxx/node_modules/deasync/build.js'`

But it can work normally in my local window environment （same node version，same deasync version）

**Comment by jasWude** [comment]
Same here.

**Comment by YangLG-7** [comment]
> Same here.

just ignore  use `npm install --ignore-scripts` @jasWude

**Comment by jasWude** [comment]
> > Same here.
> 
> just ignore use `npm install --ignore-scripts` @jasWude

Yes, it work! Thanks a lot!

**Comment by YangLG-7** [comment]
OK~ I closed
