### ISSUE TITLE
fatal error C1083: Cannot open include file: 'napi.h': No such file or directory 

### ISSUE THREAD

**Issue by fupengl** [abbr/deasync#174]
`node:18` Dependency installation failed

https://pipelines.actions.githubusercontent.com/serviceHosts/13dc2994-925a-4b6e-872c-040384caeb54/_apis/pipelines/1/runs/196/signedlogcontent/7?urlExpires=2022-08-06T09%3A45%3A24.0981126Z&urlSigningMethod=HMACV1&urlSignature=RgOVZJfauvm%2F9vK14JjvJWx7dowWbg8zZBg7bPgICQ4%3D

**Comment by abbr** [comment]
fixed with v0.1.28

**Comment by fupengl** [comment]
thanks
