### ISSUE TITLE
Update docs or logging in console regarding compatibility with node versions

### ISSUE THREAD

**Issue by steebchen** [abbr/deasync#22]
Please update your docs to clarify that the user has to use a node version >v0.11. I didn't notice it, and I spent hours to find out that it's not working with v0.10 (with mongoose queries). You could also print an error in the console that it needs a newer version (I would prefer that you do both).
The `engines` field in the package.json is advisory only and you won't notice it.
Thank you!

**Comment by abbr** [comment]
Thanks for the suggestion and sorry about the confusion.
Docs updated.
