### ISSUE TITLE
cannot build on io.js 2.3.1 && npm 2.11.3

### ISSUE THREAD

**Issue by mr-kelly** [abbr/deasync#25]

**Comment by iamsebastian** [comment]
This is your fix:
https://github.com/iamsebastian/deasync/commit/86b811f97c9deeae7c8f1faef2792226bed103ce

Or update to iojs 2.4.0 -- this also fixed my issue with deasync

**Comment by webcaetano** [comment]
I have iojs 2.5.0 and seems incompatible.
