### ISSUE TITLE
process.nextTick issue

### ISSUE THREAD

**Issue by vincekovacs** [abbr/deasync#3]
I have a library, which is using async methods. I wrapped the async methods into deasync call to call as sync.

When I call methods from function which I wrapped into process.nextTick working well, but if I call method after nextTick the deasync wont return and code execution freeze (I think it wait for response).

Example:

```javascript
function hello(callback){
  callback(null,'hello');
}

process.nextTick(function(){
  while(true){
    console.log(deasync(hello)()); // print 'hello'
  }
});

console.log(deasync(hello)()) // no result, code freeze here
```

**Comment by abbr** [comment]
There are two problems in your code:
1. function inside nextTick actually generates an infinite loop
2. You cannot differentiate the log output inside nextTick from outside.

I modified your code slightly and get expected result:

```
var deasync=require('deasync');

function hello(val, callback){
  callback(null,'hello ' + val);
}

process.nextTick(function(){
    console.log(deasync(hello)('a')); // print 'hello a'
});

console.log(deasync(hello)('b')) // print 'hello b'
```

output:
```
hello b
hello a
```
