### ISSUE TITLE
Node v4

### ISSUE THREAD

**Issue by kvnlnt** [abbr/deasync#31]
I just upgraded to Node v4. Ran an `npm install` with a package.json that uses massive js which depends on deasync. The error seems to do with deasync. Any ideas on what's going on here? 

npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! deasync@0.0.10 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.0.10 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the deasync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls deasync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kevinlint/Dev/valtworks/rawapi/npm-debug.log

**Comment by webcaetano** [comment]
Hi, 
What is the OS?

**Comment by kvnlnt** [comment]
Thanks for the response @webcaetano, should have waited to open issue....was moving too fast! I just realized massive js is pointing to deasync 0.0.10. I just installed the latest deasync and it installed fine. Must be a massive js issue...
