### ISSUE TITLE
Get error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by snowcxt** [abbr/deasync#33]

**Comment by thisredone** [comment]
Got the same thing on node v4.0.0. It does work however in v0.12.7

**Comment by abbr** [comment]
See `support` section of readme.

**Comment by AlexZeitler** [comment]
I'm facing this when using Massive-js (which uses deasync) on Node.js 4.0.0+.
< Node.js 4.0.0 works fine.

**Comment by kevinejohn** [comment]
I just got this error upgrading from Node.JS 4.0.0 to 4.1.2. Used in node-etcd

**Comment by abbr** [comment]
Just published v0.1.3 to use same pre-built binaries for same node major version. Should address some installation problems for Node 4.1+.

**Comment by AlexZeitler** [comment]
Seems to work now - even with 5.0.0, thanks :+1:

**Comment by jadbox** [comment]
Seems to be breaking with v5.11 and v6
#58

**Comment by rainabba** [comment]
Wasn't broken for me in v6.x, but I am seeing this now with v7.x
