### ISSUE TITLE
Use mongoose with deasync - what is the right way?

### ISSUE THREAD

**Issue by tomerb15** [abbr/deasync#37]
Hey, thanks for the library!

in your "Usages" section you refer to standard and non-standard API signatures.
I was wondering which approach will best suit the find() method of mongoose?
A code example will be great.

Thanks!

**Comment by abbr** [comment]
Mongoose `find` has standard API signature so you can use first option:
```
var deasync = require('deasync');
var find = deasync(Model.find);
var result;
try{
  result = find({...});
}
catch(err){
  console.log(err);
}
```
