### ISSUE TITLE
process.exit before it's finished

### ISSUE THREAD

**Issue by AminaG** [abbr/deasync#39]
The code below should run `a` function and show on the screen twice `incallback`. 

		var i=0
		setInterval(function(){
			i++;
			console.log(i)
			if(i==20) process.exit()
		},100)

		console.log('start')
		require('deasync')(a)()
		console.log('middle')
		require('deasync')(a)()

		function a(callback){
			setTimeout(function(){
				console.log('incallback')
				callback(null)
			},1500)
		}

The is the results:

		start
		1
		2
		3
		4
		5
		6
		7
		8
		9
		10
		11
		12
		13
		incallback
		middle
		14
		15
		16
		17
		18
		19
		20
		[Finished in 2.3s]

As You can see the `a` func called only once

**Comment by shinichy** [comment]
second require('deasync')(a)() starts after 1500ms, so i == 20 isn't enough.
If you change it to i == 30, the output becomes below.

```
start
1
2
3
4
5
6
7
8
9
10
11
12
13
14
incallback
middle
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
incallback
30
```

**Comment by AminaG** [comment]
I know. But this is not the expected behavior.
Generally NodeJS App, needs to wait, to any setInterval, or setTimeout to complete.

I afraid the other apps, that using setInterval/setTimeout will exit in the middle. 
Do I have what to worry about?

**Comment by shinichy** [comment]
I think that is the case if you don't call process.exit. If you call it, Node.js app exits immediately even in the middle of setInterval or setTimeout.

**Comment by AminaG** [comment]
You right
