### ISSUE TITLE
Performance Question

### ISSUE THREAD

**Issue by AminaG** [abbr/deasync#41]
I want to convert LOT OF FUNCTIONS, to deasync functions every time that app process starts...

like this:

     var fs=require('fs')
     var newFunctions={};
     for(var i in fs)
       newFunctions[i]=deasync(fs(i)
     
     fs=require('anyotherlibrary_like_mysql_mongodb_else')
     for(var i in fs)
       newFunctions[i]=deasync(fs(i)

I am not asking about best practice (is not).
My question is, How many Memory, and CPU deasync using, for creating & storing the deasync's versions of functions.

**Comment by abbr** [comment]
`deasync` CPU overhead is about 1%. Memory footprint should be neglectable.
