### ISSUE TITLE
"module.exports.loopUntil" should say "module.exports.loopWhile"

### ISSUE THREAD

**Issue by drodsou** [abbr/deasync#46]
There is an error in **index.js** line 69, it says

> module.exports.loopUntil = function(pred){ 

when it should say

> module.exports.loopWhile = function(pred){

loopWhile is referenced by **deasync** function (line 44) but is not defined, and loopUntil in fact behaves as loopWhile

**Comment by abbr** [comment]
@drodsou, thanks for catching the error. I've fixed it. Fortunately the code was not published to npm.

**Comment by drodsou** [comment]
Great!
