### ISSUE TITLE
Invoking object methods loses object context

### ISSUE THREAD

**Issue by xyleen** [abbr/deasync#5]
Hey!

The issue:
when invoking _deasync(obj.fun)_, where _obj_ is an object created with 'new' (and perhaps with some fields populated in its contructor), the object context and its fields are lost, due to [this line](https://github.com/abbr/deasync/blob/master/index.js#L28). This will probably lead to an Error due to use of undefined variables in _obj.fun_.

My test case (using [gift library](https://github.com/notatestuser/gift)):

```javascript
// git.js
var deasync = require('deasync');
var gift = require('gift');

var git = module.exports = function (repoPath) {
    var repo = gift(repoPath);

    // Following commented code works works:
    // var done = false;
    // var head = null;
    // var err = null;

    // repo.branch(function (terr, thead) {
    //     if (err) { err = terr; }
    //     head = thead;
    //     done = true;
    // });

    // while (!done) {
    //     deasync.runLoopOnce();
    // }

    // if (err) { throw err; }
    // if (!head) { throw new Error('Could not load git branch data'); }
    // return head;

    // But this fails:
    var branchSync = deasync(repo.branch);
    var head = branchSync();

    return head;
};
```

```javascript
// app.js
var GIT_DATA = require('./git')(__dirname);
```

There is a Git repository at /home/example/path/.git

Commented code fails with:
```
Error: ENOENT, open 'undefined/HEAD'
    at Function.module.exports.runLoopOnce (/home/example/path/node_modules/deasync/index.js:54:10)
    at /home/example/path/node_modules/deasync/index.js:31:19
    at module.exports (/home/example/path/git.js:29:16)
    at Object.<anonymous> (/home/example/path/app.js:33:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```
The fail happens because _repo_ object loses it's _this.dot\_git_ field (because of the deasync invoke) and tries to open a file with path:
```this.dot_git + '/HEAD'```

**Comment by abbr** [comment]
I haven't tried your code but I can reproduce the problem you described.

The problem is not specific to `deasync` and there are some generic solutions as described in [this stackoverflow posting](http://stackoverflow.com/questions/20279484/how-to-access-the-correct-this-context-inside-a-callback). In particular, you can pass `this` to the callback function using `bind` as elaborated in the answer section `Explicitly set this of the callback - part 1`. To that end, I don't see the need to provide a fix.

The code I use to 'reproduce' and verify the generic solution is:

```
var deasync = require('deasync');
function MyObject(p0) {
    this.v0 = p0;
    this.foo = function(cb) {
        console.log('this.v0=' + this.v0);
        setTimeout((function(){
            if (cb) cb(null, this.v0);
        }).bind(this),100);
    };
}

var myObj = new MyObject("abbr");
// if omitting .bind(myObj), output will be undefined
var myFoo = deasync(myObj.foo.bind(myObj));
console.log(myFoo());
```

output
```
this.v0=abbr
abbr
```
