### ISSUE TITLE
Unsupported (?) architecture: `arm64`

### ISSUE THREAD

**Issue by segfault1978** [abbr/deasync#54]
Installing the module on ARM64 platform fails with the above message. Output of NPM is:

`npm ERR! Linux 3.10.61+
npm ERR! argv "/opt/nodeAPI/bin/Linux-aarch64/node-v4.4.3-linux-arm64/bin/node" "/opt/nodeAPI/bin/Linux-aarch64/node-v4.4.3-linux-arm64/bin/npm" "install" "deasync"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! deasync@0.1.4 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.4 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the deasync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs deasync
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls deasync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/nodeAPI/bin/Linux-aarch64/node-v4.4.3-linux-arm64/bin/npm-debug.log`

Error logfile is attached.
[npm-debug.log.zip](https://github.com/abbr/deasync/files/223843/npm-debug.log.zip)

**Comment by abbr** [comment]
`deasync` only contains pre-compiled binary for platforms listed in https://github.com/abbr/deasync-bin. On other platforms you need to setup proper build tools by following installation instruction in readme.
