### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by ellioseven** [abbr/deasync#56]
Hi there,

I am using node v5.10.1 && npm  v3.8.3 trying to npm install deasync@ deasync@0.1.4.

I am on Yosimite 10.10.5.

I keep getting:

```
411 error Failed at the deasync@0.1.4 install script 'node ./build.js'.
```

Anyone have any insight into this? I am attaching the log.

[npm-debug.log.txt](https://github.com/abbr/deasync/files/229156/npm-debug.log.txt)

**Comment by abbr** [comment]
Just published `deasync@0.1.5` to add pre-compiled binary for Node 5 on OSX.
