### ISSUE TITLE
Erro to install JHIPSTER in ubuntu 16.04 with npm

### ISSUE THREAD

**Issue by juceliohv** [abbr/deasync#60]
414 error If you do, this is most likely a problem with the deasync package,
414 error not with npm itself.
414 error Tell the author that this fails on your system:
414 error     node ./build.js
414 error You can get information on how to open an issue for this project with:
414 error     npm bugs deasync
414 error Or if that isn't available, you can get their info via:
414 error     npm owner ls deasync
414 error There is likely additional logging output above.
415 verbose exit [ 1, true ]

**Comment by abbr** [comment]
What's the node version?

**Comment by juceliohv** [comment]
I solve it.

I'm running without install Bower and Gulp. I reinstall node, and after i install Gulp.

After this steps, he works.

Tank you for your help!
