### ISSUE TITLE
Deasync Not Building in Windows 10 and VS Code

### ISSUE THREAD

**Issue by MarkPhillips** [abbr/deasync#65]
I am following pluralsight "node application patterns" course.
secondthought is not being installed and returns build error in deasync.

![secondthought-build-failure-on-deasync](https://cloud.githubusercontent.com/assets/4471426/18019494/5c6d69ec-6baa-11e6-8667-6e3dd5b5325e.PNG)

grunt installDb cannot find secondthought module:
![installdb-grunt-task](https://cloud.githubusercontent.com/assets/4471426/18019664/209c56ca-6bab-11e6-9f86-9a733d12fa51.PNG)

secondthought is not in package.json

**Comment by abbr** [comment]
The referenced version of `deasync` is too old. Ask the author of the referencing module to upgrade.
