### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by checksummaster** [abbr/deasync#67]
If possible, add in build.js "arm64" as compatible target. 
"npm install deasync" give "Unsupported (?) architecture: arm64" 

but "git clone https://github.com/abbr/deasync.git" + "add in file build.js arm64" + "node build.js" work. 

using it in termux (with node-gyp onboard) on a Android P6.

**Comment by abbr** [comment]
Added in v0.1.8. 
Thanks for the comments.
