### ISSUE TITLE
run fail

### ISSUE THREAD

**Issue by kildem** [abbr/deasync#7]
I'm trying to use deasync with xslt4node
var result = deasync(xslt4node.transform)(config);
but after I get the result the app crash and I get this result:

    Assertion failed: (handle->type == UV_TCP || handle->type == UV_TTY || handle->type ==     UV_NAMED_PIPE), function uv___stream_fd, file ../deps/uv/src/unix/stream.c, line 1510.
    Abort trap: 6

and after several attempts, sometime I get this message:

    #
    # JRE version: Java(TM) SE Runtime Environment (8.0_25-b17) (build 1.8.0_25-b17)
    # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.25-b02 mixed mode bsd-amd64 compressed oops)
    # Problematic frame:
    # C  [node+0x65d0e4]  uv___stream_fd+0x34
    #
    # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c     unlimited" 
    before starting Java again
    #
    # An error report file with more information is saved as:
    # /Users/..../hs_err_pid2316.log
    #
    # If you would like to submit a bug report, please visit:
    #   http://bugreport.sun.com/bugreport/crash.jsp
    # The crash happened outside the Java Virtual Machine in native code.
    # See problematic frame for where to report the bug.
    #
    Abort trap: 6

if I don't use deasync I do not get these message, but my function require sync result ... any suggestion? (help)

**Comment by abbr** [comment]
How do you use Node/npm inside jvm?
Have you installed deasync@0.0.7 or earlier version, then upgraded Node recently to v0.11 or 0.12? If so, uninstall deasync and re-install latest version 0.0.10.

**Comment by kildem** [comment]
I'm using deasync "version": "0.0.10",
node v0.12.0, npm 2.5.1

**Comment by kildem** [comment]
I'm trying to update this code (that doesn't work with node v0.12):

            var xslt = require('node_xslt');
            var stylesheet = xslt.readXsltString(transformXslt);
            var document = xslt.readXmlString(metadata);
            var paramArray = [
                'SerivceUri', "'" + cnf.SerivceUri + "'",
                'EntityBaseClass', "'" + cnf.EntityBaseClass + "'",
                'ContextBaseClass', "'" + cnf.ContextBaseClass + "'",
                'AutoCreateContext', "'" + cnf.AutoCreateContext + "'",
                'ContextInstanceName', "'" + cnf.ContextInstanceName + "'",
                'EntitySetBaseClass', "'" + cnf.EntitySetBaseClass + "'",
                'CollectionBaseClass', "'" + cnf.CollectionBaseClass + "'",
                'DefaultNamespace', "'" + cnf.DefaultNamespace + "'",
                'MaxDataserviceVersion', "'" + (versionInfo.maxVersion || '3.0') + "'",
                'AllowedTypesList', "'" + cnf.typeFilter + "'",
                'GenerateNavigationProperties', "'" + cnf.navigation + "'"
            ];
            var result = xslt.transform(stylesheet, document, paramArray);

with:

            var xslt4node = require('xslt4node');
            var config = {
              xslt: transformXslt,
              source: metadata,
              result: String,
              params: {
                'SerivceUri':  cnf.SerivceUri,
                'EntityBaseClass': cnf.EntityBaseClass,
                'ContextBaseClass': cnf.ContextBaseClass,
                'AutoCreateContext': cnf.AutoCreateContext ,
                'ContextInstanceName': cnf.ContextInstanceName ,
                'EntitySetBaseClass':  cnf.EntitySetBaseClass,
                'CollectionBaseClass':  cnf.CollectionBaseClass ,
                'DefaultNamespace':  cnf.DefaultNamespace ,
                'MaxDataserviceVersion':  (versionInfo.maxVersion || '3.0') ,
                'AllowedTypesList':  cnf.typeFilter ,
                'GenerateNavigationProperties':  cnf.navigation 
              }
            };
            var deasync = require('deasync');
            var result = deasync(xslt4node.transform)(config);

**Comment by abbr** [comment]
This forum is intended to troubleshoot `deasync` problems, not your application problems. I don't see any correlation between your error message and `deasync`. *if I don't use deasync I do not get these message* isn't good enough to prove `deasync` is the root cause. Also your code is obviously not self-contained to reproduce the problem. I will therefore close the ticket.
