### ISSUE TITLE
ERROR in ./~/deasync/index.js

### ISSUE THREAD

**Issue by drveresh** [abbr/deasync#70]
Got tonne of errors after just installing and importing it.

ERROR in ./~/deasync/index.js
Critical dependencies:
31:12-28 the request of a dependency is an expression
 @ ./~/deasync/index.js 31:12-28

ERROR in ./~/deasync/index.js
Module not found: Error: Cannot resolve module 'fs' in /Users/.../node_modules/deasync
 @ ./~/deasync/index.js 11:10-23

ERROR in ./~/bindings/bindings.js
Module not found: Error: Cannot resolve module 'fs' in /Users/../node_modules/bindings
 @ ./~/bindings/bindings.js 6:9-22

ERROR in ./~/deasync/test.js
Module not found: Error: Cannot resolve module 'child_process' in /Users/../node_modules/deasync
 @ ./~/deasync/test.js 2:9-33

**Comment by abbr** [comment]
The directory structure in your output indicates you are not following the installation instruction.
