### ISSUE TITLE
"EBUSY: resource busy or locked" error when attempting to overwrite files

### ISSUE THREAD

**Issue by BennyH26** [abbr/deasync#72]
When an active application has called `require('deasync')`, existing source files cannot be overwritten (via `npm update`, `yarn upgrade` or similar) until the application has been closed

`error EBUSY: resource busy or locked, open 'myApplication\node_modules\deasync\bin\win32-ia32-node-6\deasync.node'
    at Error (native)`

Attempts to delete `deasync` from require.cache do not resolve the issue.

**Comment by abbr** [comment]
this is typical windows behavior handling .dll files, not the problem of deasync.

**Comment by BennyH26** [comment]
Understood.  Do you know of any workarounds?
