### ISSUE TITLE
Not Support Node version 7

### ISSUE THREAD

**Issue by Fov6363** [abbr/deasync#73]
when I run it to node v7.1.0,it no work,but i check to node v6.9.1.it work.
os:osx 10.11

**Comment by schickling** [comment]
Running into the same problem unfortunately. Any update on this @abbr?

**Comment by abbr** [comment]
which deasync version do you use?

**Comment by schickling** [comment]
```
├─ deasync@0.1.9
│  ├─ bindings@~1.2.1
│  └─ nan@^2.0.7
```

**Comment by Fov6363** [comment]
my deasync version is v0.1.8,node version is v7.1.0

**Comment by abbr** [comment]
deasync@0.1.9 is supposed to support Node@7. @schickling, are you also on os:osx 10.11?

**Comment by Fov6363** [comment]
I update deasync@0.1.9,it has support.os:osx 10.11
