### ISSUE TITLE
build fail in s390x platform

### ISSUE THREAD

**Issue by jn1981** [abbr/deasync#76]
I failed to build version 0.1.19 in s390x server. Beacause the build.js no s390x suppot.
if (!{
		ia32: true,
		x64: true,
		arm: true,
		arm64: true,
		ppc64: true,
		ppc: true
	}.hasOwnProperty(arch)) {
	console.error('Unsupported (?) architecture: `' + arch + '`');
	process.exit(1);
}

May be need change code like:
if (!{
		ia32: true,
		x64: true,
		arm: true,
		arm64: true,
		ppc64: true,
		ppc: true,
                s390x: true
	}.hasOwnProperty(arch)) {
	console.error('Unsupported (?) architecture: `' + arch + '`');
	process.exit(1);
}

**Comment by abbr** [comment]
I have no way to test the platform, not to mention supplying pre-built binary. If you updated build.js and working, feel free to submit a PR.

**Comment by jn1981** [comment]
thanks
