### ISSUE TITLE
Not an issue, but a ATTA BOY!!!

### ISSUE THREAD

**Issue by FairSite2C** [abbr/deasync#80]
I was totally digging promises and awaits in node 7 until I hit the snap await doesn't work in non async functions. Using es6 class pattern no constructor or function can be marked async. MAJOR BUMMER. 

deasync to me is await for nonasync procedures. I guess I don't understand the full tech ramifications but to me folks who just sing hymns to await but wail at this duplicate function for use in sync procedures make little sense to me.

This let me pass parameters into a nonasync function, pass the same parameters down an async chain that modify them and return them to the original calling function AS expected.

Pretty cool and exactly what I needed. Thanks.

**Comment by abbr** [comment]
Glad you found it useful.
