### ISSUE TITLE
A Fair Request

### ISSUE THREAD

**Issue by lachrist** [abbr/deasync#83]
Thanks a lot for this awesome module!

I want to use it for simulating synchronous remote communications inside a single node process. The client code being synchronous and the server handlers being asynchronous I need to transform the server handlers into synchronous functions to preserve the calling context. Unfortunately my use cases involve nested communications which deasync does not seem to support because it is unfair.

Below is an example that demonstrate what I mean by the unfairness of deasync.
I tried but I don't see how I can implement fairness with the current deasync interface.
If it is indeed not the case, would it be possible to implement fairness inside deasync?

Thanks a lot,
Laurent

```js
var Deasync = require("deasync");
console.log("I love deasync but it's unfair");
var counter1 = 0;
var counter2 = 0;
setImmediate(function () {
  while (counter2 < 5) {
    console.log("loop2", counter2++);
    Deasync.runLoopOnce();
  }
});
while (counter1 < 5) {
  console.log("loop1", counter1++);
  Deasync.runLoopOnce();
}
console.log("Which might cause deadlock");
var counter = 0;
var pending = true;
setImmediate(function () {
  while (pending) {
    Deasync.runLoopOnce();
  }
});
while (counter < 5) {
  Deasync.runLoopOnce();
}
var pending = false;
console.log("This will never be printed");
```

```
I love deasync but it's unfair
loop1 0
loop2 0
loop2 1
loop2 2
loop2 3
loop2 4
loop1 1
loop1 2
loop1 3
loop1 4
Which might cause deadlock
^C
```

**Comment by abbr** [comment]
I don't see any nested communications or even a simulation of which in your code. The output is all expected.

**Comment by lachrist** [comment]
Thanks for the answer!

1. I did not include my nested communication for clarity reason. If you want I can provide such code.
2. I made an error by not incrementing my last loop on the snippet of my previous post. I put the corrected version below (it still does not terminate).

Sorry for being unclear. The behavior (not the bug) I have problem with is that deasync only tries to make progress on the context that was last spawn into the system. This is depicted in `preempted.js` which does not interleaves the logs `loop1` and `loop2`. _loop1_ is preempted by _loop2_ and is only resumed after _loop2_ ran to completion. In the case of `lifelock.js` this causes a lifelock because _loop_ must be run 5 times before letting _pending_ run to completion.

```js
// preempted.js
var counter1 = 0;
var counter2 = 0;
setImmediate(function () {
  // context loop2
  while (counter2 < 5) {
    console.log("loop2", counter2++);
    Deasync.runLoopOnce();
  }
});
// context loop1
while (counter1 < 5) {
  console.log("loop1", counter1++);
  Deasync.runLoopOnce();
}
```


```js
// lifelock.js
var counter = 0;
var pending = true;
setImmediate(function () {
  // context pending
  while (pending) {
    Deasync.runLoopOnce();
  }
});
// context loop
while (counter < 5) {
  console.log("loop", counter++);
  Deasync.runLoopOnce();
}
var pending = false;
```

My question is the following. Everytime an event spawn into the system, deasync may stop the computation and serialize the context so that the computation can be resumed later. Would it be possible for deasync to try to make progress in every serialized context in turn (fair) rather than trying to make in progress in the last one (unfair)?

Best,
Laurent

**Comment by abbr** [comment]
Thanks for clarifying. I think your request is fair. But doesn't seem to be trivial to achieve. deasync essentially just relays runLoopOnce to underlying libuv of nodejs. If multiple runLoopOnce are registered, the order of return is controlled by libuv.

**Comment by lachrist** [comment]
That answers my question.
Thanks for your time and your work on deasync!

Cheers,
Laurent
