### ISSUE TITLE
Changing the functions context gives me trouble

### ISSUE THREAD

**Issue by delijah** [abbr/deasync#88]
By using fn.apply https://github.com/abbr/deasync/blob/60fbfa97f26a79ccf918d1d3188ac3a7e0d685ff/index.js#L43 you are changing the context of the function to be called. This gives me trouble when calling a function of a third-party library (because it will use `this...`).

Any possibility you do it without changing the context?

**Comment by abbr** [comment]
Seems to be a duplication of #5 where solution is provided.

**Comment by delijah** [comment]
Thank you for your quick response. I have tried bind already, but it doesn't work, since i do not have access to the original class which is used by the function. So the solutions described in #5 and its links do not work for this case.

**Comment by abbr** [comment]
Can you post your code snippet using deasync?

**Comment by delijah** [comment]
```
import deasync from 'deasync';
import sharp from 'sharp';

sharp.prototype.toBufferSync = function(options) {
    const syncToBuffer = deasync(this.toBuffer.bind(this));

    return syncToBuffer({
        ...options,
        resolveWithObject: true,
    });
};

export default sharp;
```

**Comment by delijah** [comment]
If i would not have been trying that already, i would not bother you with an issue over here.

Same error.
