### ISSUE TITLE
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.

### ISSUE THREAD

**Issue by BennyH26** [abbr/deasync#91]
On deasync v0.1.12 on Windows 10, I'm receiving a strange error on Node v8.9.3 with the following code:

The loop runs maybe 8-10 times, then generates:

`FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.`

```
deasync.loopWhile(function () {
    return !databaseConnectionsInitialized;
});
```

`databaseConnectionsInitialized` is a boolean value.

Any thoughts?

**Comment by abbr** [comment]
How can you tell the error is created/caused by deasync?

**Comment by BennyH26** [comment]
My apologizes, this was **NOT** a desync related issue.

**Comment by Zaseth** [comment]
@BennyH26 Have you fixed this? I'm having it!

https://github.com/substack/tape/issues/491
